name: Build, test, deploy and cleanup

on:
  push:
    branches:
      - main
  delete:
    branches-ignore:
      - main
  pull_request:
    types:
      - closed

jobs:
  build-test-deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run linting check
        run: npm run check

      - name: Start HTTP server and run tests
        run: |
          npx http-server ./src &
          sleep 5
          npx playwright test

      - name: Run build script
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: ${{ github.ref_name }}

  cleanup:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'delete' && github.event.ref_type == 'branch' && github.ref != 'refs/heads/main') ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')

    steps:
      - name: Delete Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          elif [[ "${{ github.event_name }}" == "delete" ]]; then
            BRANCH_NAME="${{ github.ref }}"
            BRANCH_NAME="${BRANCH_NAME#refs/heads/}"
          else
            echo "Unsupported event type: ${{ github.event_name }}"
            exit 1
          fi

          echo "Deleting branch $BRANCH_NAME"

          curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME"